---
- name: install basic modules
  yum: >
    name={{ item }}
    state=installed
  with_items:
    - jq
    - nkf
    - ntp
    - screen
    - tree
    - wget
    - zsh
- name: install japanese support
  yum: >
    name={{ item }}
  with_items:
    - "@japanese-support"
- name: set JST timezone
  shell: cp -p /usr/share/zoneinfo/Japan /etc/localtime
  changed_when: false
