---
- name: install httpd
  yum: >
    name={{ item }}
    state=installed
  with_items:
    - httpd
    - php
- name: Place apache config
  template: >
    src=httpd.conf
    dest=/etc/httpd/conf/httpd.conf
    mode=0644
    owner=root
    group=root
  notify:
    - restart httpd
