---
- name: set mysql epel repository
  yum: >
    name=http://dev.mysql.com/get/mysql-community-release-el6-5.noarch.rpm
    state=present
- name: install MySQL
  yum: >
    name={{ item }}
    state=installed
  with_items:
    - mysql-community-server
    - MySQL-python
- name: place mysql conf file
  template: >
    src=my.cnf
    dest=/etc/my.cnf
    mode=0644
    owner=root
    group=root
  notify:
    - restart MySQL
#- name: create database user with name 'vagrant' and password 'vagrant_pass' with all database privileges
-  mysql_user: >
    name=vagrant
    password=vagrant_pass
    priv=*.*:ALL
    state=present
- name: start MySQL
  service: >
    name=mysqld
    state=running
    enabled=yes
